#!/bin/bash

# Getting list of all hard disks
ALLDEVICES="$(ls -1 /dev/sd?)"
DEVICES=""
INSTALLATIONDEVICE=""
CLOUDCONFIGFILE="cloud-config.yml"
IGNITIONFILE="coreos-install.json"

clear
echo "Please choose the device for CoreOS installation."

select choice in ${ALLDEVICES} abort
do
  case "${choice}" in
    abort)  echo "The installation is aborted."; exit 0 ;;
       "")  echo "Invalid selection" ;;
        *)  clear
            echo "You choose ${choice} for installation."
            echo ""
            INSTALLATIONDEVICE=$choice
            break ;;  
  esac
done

for device in ${ALLDEVICES}
do
   if [[ "${device}" != "${INSTALLATIONDEVICE}" ]]; then
     DEVICES="${DEVICES} ${device}"
   fi
done

if [[ "${DEVICES}" != "" ]]; then
  echo -n "Do you want to use/format an additional disk (y/N)? "
  read answer
  if [[ ${answer} = "y" || ${answer} = "Y" ]] ; then
    select choice in ${DEVICES} end
    do
      case "${choice}" in
        abort|end)  break ;;
               "")  echo "Invalid selection" ;;
                *)  echo "Please enter the label for the partiton ${choice}1." 
                    echo -n "Label > "
                    read LABEL 
                    if [[ "${LABEL}" != "" ]]; then
		      sgdisk -Z "${choice}" > /dev/null 2>&1 &&
                      sgdisk -n 1:0:0 -c 1:"${LABEL}" "${choice}" > /dev/null 2>&1 &&
                      mkfs.ext4 "${choice}1" > /dev/null 2>&1
                      if [[ $? = 0 ]] ; then
                        echo "The operation has completed successfully for the device ${choice}."
                        echo ""
                      else
                        echo "An error has occurred. Please check the device."
                        exit 1
                      fi
                    else 
                      echo "The label is required. Please try again." 
                      echo ""
                    fi ;;
      esac
    done
  else
    echo "Only the device ${INSTALLATIONDEVICE} will be used for this installation."
    echo ""
  fi
fi

echo "Now coreos will be installed an ${INSTALLATIONDEVICE}."
echo "Do you want to use a cloud config or an ignition file?"
echo -n "Type 'c' for cloud config or 'i' for ignition. "
read answer

if [[ "${answer}" = "C" || "${answer}" = "c" ]] ; then
  echo -n "Do you want to use your own cloud config file (y/N)? "
  read answer
  if [[ "${answer}" = "y" || "${answer}" = "Y" ]] ; then
    echo "Please enter the full path to youre file."
    read CLOUDCONFIGFILE
  fi
  echo "Begin installation."
  ./coreos-offline-install -d "${INSTALLATIONDEVICE}" -c "${CLOUDCONFIGFILE}" -a /media/setup/app_install
elif [[ "${answer}" = "I" || "${answer}" = "i" ]]; then
  echo -n "Do you want to use your own ignition file (y/N)? "
  read answer
  if [[ "${answer}" = "y" || "${answer}" = "Y" ]] ; then
    echo "Please enter the full path to youre file."
    read IGNITIONFILE
  fi
  echo "Begin installation."
  ./coreos-offline-install -d "${INSTALLATIONDEVICE}" -i "${IGNITIONFILE}" -a /media/setup/app_install
else 
  echo "You didn't choose a configuration file for the coreos installation."
  echo "Because it is recomented to use one we abort here."
  echo "All changes on the hard drives will be persist."
  echo "To install coreos use the script coreos-offline-install."
fi

