#!/bin/bash

# Getting list of all hard disks
ALLDEVICES="$(ls -1 /dev/sd?)"
DEVICES=""
INSTALLATIONDEVICE=""

clear
echo "Please choose the device for CoreOS installation."

select choice in ${ALLDEVICES} abort
do
  case "${choice}" in
    abort)  echo "The installation is aborted."; exit 0 ;;
       "")  echo "Invalid selection" ;;
        *)  clear
            echo "You choose ${choice} for installation."
            echo ""
            INSTALLATIONDEVICE=$choice
            break ;;  
  esac
done

for device in ${ALLDEVICES}
do
   if [[ "${device}" != "${INSTALLATIONDEVICE}" ]]; then
     DEVICES="${DEVICES} ${device}"
   fi
done

if [[ "${DEVICES}" != "" ]]; then
  echo -n "Do you want to use/format an additional disk (y/N)? "
  read answer
  if [[ ${answer} = "y" || ${answer} = "Y" ]] ; then
    select choice in ${DEVICES} end
    do
      case "${choice}" in
        abort|end)  break ;;
               "")  echo "Invalid selection" ;;
                *)  echo "Please enter the label for the partiton ${choice}1." 
                    echo -n "Label > "
                    read LABEL 
                    if [[ "${LABEL}" != "" ]]; then
		      sgdisk -Z "${choice}" > /dev/null 2>&1 &&
                      sgdisk -n 1:0:0 -c 1:"${LABEL}" "${choice}" > /dev/null 2>&1 &&
                      mkfs.ext3 "${choice}1" > /dev/null 2>&1
                      if [[ $? = 0 ]] ; then
                        echo "The operation has completed successfully for the device ${choice}."
                        echo ""
                      else
                        echo "An error has occurred. Please check the device."
                        exit 1
                      fi
                    else 
                      echo "The label is required. Please try again." 
                      echo ""
                    fi ;;
      esac
    done
  else
    echo "Only the device ${INSTALLATIONDEVICE} will be used for this installation."
    echo ""
  fi
fi

./coreos-offline-install -d ${INSTALLATIONDEVICE} -i coreos-install.json -a /media/setup/app_install
